@LibraryApplicationProject_HostAddress = https://localhost:7050

GET {{LibraryApplicationProject_HostAddress}}/api/loans

###

GET {{LibraryApplicationProject_HostAddress}}/api/isbns

###
GET {{LibraryApplicationProject_HostAddress}}/api/authors

###

POST {{LibraryApplicationProject_HostAddress}}/api/loans/loanbooks
Content-Type: application/json

{
  //LoanDTOEntry
}

###
